-- CREATE OR REPLACE TABLE TargetColumnDetails AS
SELECT 
    OBJECT_KEYS(f.value)[0]::STRING AS column_name,
    f2.value[0]::STRING AS datatype,
    UPPER(f2.value[1]::STRING) AS action_type
FROM TABLE(
    FLATTEN(
        INPUT => PARSE_JSON('{
        "target_table": "MAIN.PUBLIC.EMPLOYEEDETAILS_INCREMENTAL", 
          "result": [
            { "AGE": ["NUMBER", "ADD"] },
            { "ADDRESS": ["STRING", "DELETE"] },
            { "HIREDATE": ["TIMESTAMP", "DELETE"] }
          ]
        }'):"result"
    )
) AS f,
TABLE(FLATTEN(INPUT => f.value)) AS f2;




SELECT 
    payload:"target_table"::STRING AS target_table,
    OBJECT_KEYS(f.value)[0]::STRING AS column_name,
    f2.value[0]::STRING AS datatype,
    UPPER(f2.value[1]::STRING) AS action_type
FROM TABLE(
    FLATTEN(
        INPUT => PARSE_JSON('{
        "target_table": "MAIN.PUBLIC.EMPLOYEEDETAILS_INCREMENTAL", 
          "result": [
            { "AGE": ["NUMBER", "ADD"] },
            { "ADDRESS": ["STRING", "DELETE"] },
            { "HIREDATE": ["TIMESTAMP", "DELETE"] }
          ]
        }'):"result"
    )
) AS f,
    TABLE(FLATTEN(INPUT => f.value)) AS f2;
     

WITH data AS (
  SELECT 
    PARSE_JSON('{
      "target_table": "MAIN.PUBLIC.EMPLOYEEDETAILS_INCREMENTAL", 
      "result": [
        { "AGE": ["NUMBER", "ADD"] },
        { "ADDRESS": ["STRING", "DELETE"] },
        { "HIREDATE": ["TIMESTAMP", "DELETE"] }
      ]
    }') AS payload
)
SELECT 
    payload:"target_table"::STRING AS target_table,
    OBJECT_KEYS(f.value)[0]::STRING AS column_name,
    f2.value[0]::STRING AS datatype,
    UPPER(f2.value[1]::STRING) AS action_type
FROM data,
     TABLE(FLATTEN(INPUT => payload:"result")) AS f,
     TABLE(FLATTEN(INPUT => f.value)) AS f2;

        
SELECT 
    PARSE_JSON(ColumnDict):"target_table"::STRING AS target_table,
    OBJECT_KEYS(f.value)[0]::STRING AS column_name,
    f2.value[0]::STRING AS datatype,
    UPPER(f2.value[1]::STRING) AS action_type
FROM TABLE(
        FLATTEN(
            INPUT => PARSE_JSON(ColumnDict):"result"
        )
     ) AS f,
     TABLE(FLATTEN(INPUT => f.value)) AS f2;



CALL MANAGE_TABLE_COLUMNS(
    'ID',
    'HIREDATE', 
    PARSE_JSON('{
        "target_table": "MAIN.PUBLIC.EMPLOYEEDETAILS_INCREMENTAL", 
        "result": [
            { "AGE": ["NUMBER", "ADD"] },
            { "ADDRESS": ["STRING", "DELETE"] },
            { "HIREDATE": ["TIMESTAMP", "DELETE"] }
        ]
    }')
);





CREATE TABLE EMPLOYEE_DETAILS3 AS SELECT * FROM EMPLOYEEDETAILS;


SELECT * FROM  EMPLOYEE_DETAILS3;

DESC TABLE EMPLOYEE_DETAILS3;

SELECT * FROM EMPLOYEEDETAILS;

ALTER TABLE EMPLOYEEDETAILS
DROP COLUMN CONTACT;


-------
CREATE TABLE EMPLOYEEDETAILS_BACKUP AS SELECT * FROM EMPLOYEEDETAILS;

CREATE TABLE EMPLOYEEDETAILS AS SELECT * FROM EMPLOYEE_DETAILS4;

CREATE TABLE EMPLOYEE_DETAILS4 AS SELECT * FROM EMPLOYEEDETAILS;


CREATE TABLE EMPLOYEEDETAILS  AS SELECT * FROM EMPLOYEEDETAILS_BACKUP;


SELECT * FROM MAIN.PUBLIC.EMPLOYEE_DETAILS4;

SELECT * FROM MAIN.PUBLIC.EMPLOYEEDETAILS;

DESC TABLE EMPLOYEEDETAILS;
DESC TABLE EMPLOYEE_DETAILS4;


ALTER TABLE EMPLOYEEDETAILS
ADD COLUMN MANAGER STRING;

ALTER TABLE EMPLOYEEDETAILS
MODIFY MANAGER VARCHAR;

ALTER TABLE EMPLOYEEDETAILS
ADD COLUMN ATTENDANCE_PERCENTAGE NUMBER(10,3);

ALTER TABLE EMPLOYEEDETAILS
MODIFY ATTENDANCE_PERCENTAGE NUMBER(20,3);


UPDATE EMPLOYEEDETAILS
SET ATTENDANCE_PERCENTAGE = 85.987
WHERE ID = 10;

-- DROP TABLE MAIN.PUBLIC.EMPLOYEEDETAILS;
-- DROP TABLE MAIN.PUBLIC.EMPLOYEE_DETAILS4;
--UNDROP TABLE MAIN.PUBLIC.EMPLOYEE_DETAILS4;

--CONTACT	NUMBER(38,0)

ALTER TABLE EMPLOYEEDETAILS 
ALTER CONTACT NUMBER(35,0);

ALTER TABLE EMPLOYEEDETAILS
ADD COLUMN CONTACT NUMBER;

ALTER TABLE EMPLOYEE_DETAILS4
DROP COLUMN CONTACT;

ALTER TABLE EMPLOYEEDETAILS
DROP COLUMN HIREDATE;--HIREDATE;

ALTER TABLE EMPLOYEEDETAILS
DROP COLUMN GENDER;

ALTER TABLE EMPLOYEE_DETAILS4
DROP COLUMN ZIPCODE;

ALTER TABLE EMPLOYEEDETAILS
ADD COLUMN ZIPCODE VARCHAR(10) DEFAULT '' NOT NULL;

ALTER TABLE EMPLOYEEDETAILS
MODIFY ZIPCODE SET NOT NULL;

ALTER TABLE EMPLOYEEDETAILS 
ALTER COLUMN ZIPCODE DROP DEFAULT;

ALTER TABLE EMPLOYEEDETAILS
MODIFY COLUMN ZIPCODE DROP NOT NULL;

ALTER TABLE EMPLOYEEDETAILS
ADD COLUMN ISDELETED NUMBER DEFAULT 0 NOT NULL;

ALTER TABLE EMPLOYEEDETAILS 
MODIFY CITY VARCHAR(60);


UPDATE  EMPLOYEEDETAILS
SET ZIPCODE = '50008'||ID
WHERE ID<>10;


SELECT '50008'||ID
FROM EMPLOYEEDETAILS;


ZIPCODE => NULL -> NOT-NULL
       => STRING -> NUMBER



ALTER TABLE EMPLOYEE_DETAILS4
DROP COLUMN ZIPCODE;
